apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: D:/volume
--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual 
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi